// @ts-check
// Autogenerated from the docs/ folder structure (order via each file's sidebar_position
// front-matter and _category_.json for sections).
//
// For users (docs/users/), the sidebar order is:
//   1. web-app  (Signing in & your settings)
//   2. extension (The capture extension)
//   3. recording (Record in the app — in-app mic recorder + PWA install)
//   4. meetings-and-export
//   5. uploads
//   6. sharing
// Each lives in its file's sidebar_position front-matter; add or reorder there.

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
