// @ts-check
// Autogenerated from the docs/ folder structure (order via each file's sidebar_position
// front-matter and _category_.json for sections).

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
