"""user token_version

Revision ID: 496430347aa1
Revises: f4fc04a3e272
Create Date: 2026-06-28 16:10:20.718072
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '496430347aa1'
down_revision: Union[str, None] = 'f4fc04a3e272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows; new inserts use the model's Python default.
    op.add_column(
        'users', sa.Column('token_version', sa.Integer(), nullable=False, server_default='0')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    # ### end Alembic commands ###
