"""initial schema

Revision ID: 9ca99ff5aa88
Revises: 
Create Date: 2026-06-27 13:58:09.025640
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ca99ff5aa88'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.Enum('teams', 'meet', name='platform'), nullable=False),
    sa.Column('external_meeting_id', sa.String(length=512), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('consent_status', sa.Enum('pending', 'granted', 'denied', 'withdrawn', name='consent_status'), nullable=False),
    sa.Column('consent_captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_meeting_id', name='uq_meeting_identity')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('platform_call_id', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('joining', 'active', 'ended', 'failed', name='session_status'), nullable=False),
    sa.Column('ended_reason', sa.String(length=64), nullable=True),
    sa.Column('run_id', sa.String(length=64), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_call_id', name='uq_session_platform_call_id')
    )
    op.create_index(op.f('ix_sessions_meeting_id'), 'sessions', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_sessions_run_id'), 'sessions', ['run_id'], unique=False)
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_table('audio_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('speaker_id', sa.String(length=128), nullable=False),
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('pending', 'recorded', 'lost', name='chunk_state'), nullable=False),
    sa.Column('start_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=True),
    sa.Column('gap_flag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'speaker_id', 'seq', name='uq_chunk_seq')
    )
    op.create_index(op.f('ix_audio_chunks_session_id'), 'audio_chunks', ['session_id'], unique=False)
    op.create_table('config_changes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('source_language_hints', postgresql.ARRAY(sa.String(length=16)), nullable=True),
    sa.Column('custom_vocabulary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('translation_targets', postgresql.ARRAY(sa.String(length=16)), nullable=True),
    sa.Column('actor', sa.String(length=256), nullable=True),
    sa.Column('config_generation', sa.Integer(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_changes_session_id'), 'config_changes', ['session_id'], unique=False)
    op.create_table('participants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('speaker_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'speaker_id', name='uq_participant_speaker')
    )
    op.create_index(op.f('ix_participants_session_id'), 'participants', ['session_id'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('speaker_id', sa.String(length=128), nullable=False),
    sa.Column('utterance_id', sa.String(length=128), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('meeting_seq', sa.BigInteger(), nullable=False),
    sa.Column('start_ts', sa.Float(), nullable=True),
    sa.Column('end_ts', sa.Float(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_language', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'speaker_id', 'utterance_id', name='uq_segment_utterance')
    )
    op.create_index(op.f('ix_transcript_segments_meeting_seq'), 'transcript_segments', ['meeting_seq'], unique=False)
    op.create_index(op.f('ix_transcript_segments_session_id'), 'transcript_segments', ['session_id'], unique=False)
    op.create_table('translations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('segment_id', sa.Uuid(), nullable=False),
    sa.Column('target_language', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_revision', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segment_id', 'target_language', name='uq_translation_target')
    )
    op.create_index(op.f('ix_translations_segment_id'), 'translations', ['segment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_translations_segment_id'), table_name='translations')
    op.drop_table('translations')
    op.drop_index(op.f('ix_transcript_segments_session_id'), table_name='transcript_segments')
    op.drop_index(op.f('ix_transcript_segments_meeting_seq'), table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index(op.f('ix_participants_session_id'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_config_changes_session_id'), table_name='config_changes')
    op.drop_table('config_changes')
    op.drop_index(op.f('ix_audio_chunks_session_id'), table_name='audio_chunks')
    op.drop_table('audio_chunks')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_run_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_meeting_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('meetings')
    # ### end Alembic commands ###
