"""meeting owner_id

Revision ID: ed95ddce895f
Revises: 496430347aa1
Create Date: 2026-06-28 16:33:01.198468
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed95ddce895f'
down_revision: Union[str, None] = '496430347aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('owner_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_meetings_owner_id'), 'meetings', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'meetings', 'users', ['owner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.drop_index(op.f('ix_meetings_owner_id'), table_name='meetings')
    op.drop_column('meetings', 'owner_id')
    # ### end Alembic commands ###
